name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: Toma62299781/waka-readme@master
        with:
          python-version: '3.10' # 制定python版本
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
